image: openjdk:22

pipelines:
  default:
    - step:
        name: Build & Test
        services:
          - docker
        script:
          - echo "Starting Selenium Grid with multiple Chrome nodes"
          - docker-compose up -d
          - sleep 60
          - chmod +x mvnw
          - ./mvnw -v
          - ./mvnw clean test
          - docker-compose down
        artifacts:
          - target/logs/executionLog.log
          - target/executionReports/IHI_Automation_Report.html

definitions:
  services:
    docker:
      memory: 1024