image: docker/compose:1.29.2

pipelines:
  default:
    - step:
        name: Build and Test with Docker Compose
        caches:
          - docker
          - maven
        script:
          - echo "Starting Docker setup without Docker-in-Docker..."
          - docker --version
          - docker-compose --version
          - docker-compose up -d
          - echo "Waiting for services to be ready..."
          - sleep 20
          - ./mvnw clean test
          - echo "Stopping Docker Compose services..."
          - docker-compose down

