image: docker:20.10.7

pipelines:
  default:
    - step:
        name: Start Docker Services and Run Tests
        services:
          - docker
        caches:
          - docker
        script:
          - echo "Starting Docker setup..."
          - docker info

          - echo "Setting up Docker Compose services..."
          - docker-compose -f docker-compose.yml up -d

          - echo "Waiting for services to start..."
          - sleep 10
          - echo "Running Maven tests with Maven Wrapper..."
          - ./mvnw clean test
          - echo "Stopping Docker Compose services..."
          - docker-compose -f docker-compose.yml down

definitions:
  services:
    docker:
      image: docker:20.10.7-dind  # Docker-in-Docker service
