image: openjdk:22

pipelines:
  default:
    - step:
        name: Build & Test
        services:
          - selenium
        script:
          - echo "Building and running automation suite."
          - chmod +x mvnw
          - ./mvnw -v
          - ./mvnw clean test
        artifacts:
          - target/logs/executionLog.log
          - target/executionReports/IHI_Automation_Report.html

definitions:
  services:
    selenium:
      image: selenium/standalone-chrome